//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothoSharedItems.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClothoSharedItems.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Settings&gt;
        ///	&lt;TL_PoutLimit&gt;
        ///		&lt;IgnoreCF&gt;Parameter,SBIN,HBIN,DIE_X,DIE_Y,SITE,TIME,TOTAL_TESTS,LOT_ID,WAFER_ID,PassFail,TimeStamp,IndexTime,PartSN,SWBinName,HWBinName,2DID,Temperature,HandlerMisc,MFG_ID,OTP_MODULE_ID,SubLot&lt;/IgnoreCF&gt;
        ///		&lt;DeltaValue&gt;0.1&lt;/DeltaValue&gt;
        ///		&lt;PoutLimitConditions&gt;
        ///			&lt;IncludeRule&gt;PT_POUT,FIXEDPOUT&lt;/IncludeRule&gt;
        ///			&lt;ExcludeRule&gt;P3DB,P2DB,P1DB,MAXGAIN,PIN&lt;/ExcludeRule&gt;
        ///		&lt;/PoutLimitConditions&gt;
        ///	&lt;/TL_PoutLimit&gt;
        ///	
        ///	&lt;GuPacakge&gt;
        ///		&lt;GuCorr&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRCMhelper {
            get {
                return ResourceManager.GetString("BRCMhelper", resourceCulture);
            }
        }
    }
}
